"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Authenticator } from "@aws-amplify/ui-react";
import { Amplify } from "aws-amplify";
import "./app.css";
import "./globals.css";
import "@aws-amplify/ui-react/styles.css";
import outputs from "@/amplify_outputs.json";
import {
  CircleUserRound,
  Database,
  FileText,
  LayoutDashboard,
} from "lucide-react";
import { MenuButton, MenuItem, Menu, MenuItems } from "@headlessui/react";

Amplify.configure(outputs);
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Authenticator className="authenticator-component">
          {({ signOut }) => (
            <div className="min-h-screen bg-gray-50">
              <nav className="bg-white shadow-sm">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                  <div className="flex justify-between h-16">
                    <div className="flex items-center">
                      <img
                        src="/querylens-icon-title.svg"
                        alt="QueryLens"
                        className="h-8"
                      />
                    </div>
                    <div className="flex items-center justify-center flex-1 space-x-8">
                      <a
                        className="text-sm font-medium text-gray-700 hover:text-gray-900 "
                        href="/overview"
                        data-discover="true"
                      >
                        <div className="flex items-center space-x-2">
                          <LayoutDashboard
                            className="w-5 h-5"
                            color="#4b5563"
                          />
                          <span>Overview</span>
                        </div>
                      </a>
                      <a
                        className="text-sm font-medium text-gray-700 hover:text-gray-900 text-gray-900"
                        href="/clusters"
                        data-discover="true"
                      >
                        <div className="flex items-center space-x-2">
                          <Database className="w-5 h-5" color="#4b5563" />
                          <span>Clusters</span>
                        </div>
                      </a>
                      <a
                        className="text-sm font-medium text-gray-700 hover:text-gray-900 "
                        href="/onboarding"
                        data-discover="true"
                      >
                        <div className="flex items-center space-x-2">
                          <FileText className="w-5 h-5" color="#4b5563" />
                          <span>Onboarding</span>
                        </div>
                      </a>
                    </div>
                    <div className="flex items-center">
                      <Menu as="div" className="relative ml-3">
                        <div>
                          <MenuButton className="relative flex rounded-full text-sm gray-800">
                            <CircleUserRound
                              className="w-5 h-5"
                              color="#4b5563"
                            />
                          </MenuButton>
                        </div>
                        <MenuItems

                          className="absolute right-0 z-10 mt-2 w-24 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black/5 transition focus:outline-none data-[closed]:scale-95 data-[closed]:transform data-[closed]:opacity-0 data-[enter]:duration-100 data-[leave]:duration-75 data-[enter]:ease-out data-[leave]:ease-in"
                        >
                          <MenuItem>
                            <button
                              className="block px-4 py-2 text-sm text-gray-700"
                              onClick={signOut}
                            >
                              Sign out
                            </button>
                          </MenuItem>
                        </MenuItems>
                      </Menu>
                    </div>
                  </div>
                </div>
              </nav>
              <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                {children}
              </main>
            </div>
          )}
        </Authenticator>
      </body>
    </html>
  );
}
